### ISSUE TITLE
Error concerning Read names while running Cannoli

### ISSUE THREAD

**Issue by snag-gh** [bigdatagenomics/cannoli#148]
Hello,

I am trying to run bwa with cannoli. 

I used the interleaveFastq command to interleave my input files. I used the following command to run cannoli on the spark cluster -
`cannoli-submit -- bwa /full/path/to/Sample_N1D_PS.ifq /full/path/to/N1D_PS.bwa.alignment.adam N1D_PS -index /full/path/to/ucsc.hg19.fasta -sequence_dictionary /full/path/to/ucsc.hg19.dict -executable /usr/local/apps/bwa/0.7.17/bwa -force_load_ifastq ` 

This is throwing an error regarding read names.

`18/11/27 12:16:15 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Thread-7,5,main]
java.lang.IllegalArgumentException: requirement failed: Reads NS500391:156:HV5LLBGX2:2:11309:20951:20401 1:N:0:NCCACTGT and NS500391:156:HV5LLBGX2:2:11309:20951:20401 2:N:0:NCCACTGT in Fragment have different names.
        at scala.Predef$.require(Predef.scala:224)
        at org.bdgenomics.adam.converters.FastqRecordConverter.convertFragment(FastqRecordConverter.scala:241)
        at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadInterleavedFastqAsFragments$1$$anonfun$apply$18.apply(ADAMContext.scala:2555)
        at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadInterleavedFastqAsFragments$1$$anonfun$apply$18.apply(ADAMContext.scala:2555)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at org.bdgenomics.adam.rdd.fragment.InterleavedFASTQInFormatter.write(InterleavedFASTQInFormatter.scala:72)
        at org.bdgenomics.adam.rdd.InFormatterRunner.run(InFormatter.scala:27)
        at java.lang.Thread.run(Thread.java:745)
18/11/27 12:16:15 INFO DiskBlockManager: Shutdown hook called
18/11/27 12:16:15 INFO ShutdownHookManager: Shutdown hook called
18/11/27 12:16:15 INFO ShutdownHookManager: Deleting directory /spin1/users/nagarajs2/spark/local/spark-3ae0ac8f-ccc1-4db6-8018-247b3e059d7b/executor-9f7cd8db-8cbd-43f7-b5fc-01f6676f07c9/spark-4ce7fbeb-03d1-4179-b467-6c2b3a7c4ad5`

I have run BWA on these fastq files separately & they are formatted correctly. I am not sure what this error means. 

Thank you.

**Comment by heuermh** [comment]
Hello @snag-gh!

I don't believe this is an issue with Cannoli per se, rather upstream in ADAM.  Could you try this with `cannoli-shell`?

```bash
$ cannoli-shell ...

scala> import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.adam.rdd.ADAMContext._

scala> val fragments = sc.loadInterleavedFastqAsFragments("/full/path/to/Sample_N1D_PS.ifq")
fragments: org.bdgenomics.adam.rdd.fragment.FragmentRDD = RDDBoundFragmentRDD with 0 reference sequences, 0 read groups, and 0 processing steps

scala> fragments.rdd.first()
res0: org.bdgenomics.formats.avro.Fragment = {"name": "H06HDADXX130110:2:2116:3345:91806",...
```

**Comment by snag-gh** [comment]
Thank you for the quick response! In case it helps, I have run ADAM transform alignments on this data set without any problems..

```
scala> import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.adam.rdd.ADAMContext._

scala> val fragments = sc.loadInterleavedFastqAsFragments("/full/path/to/Sample_N1D_PS.ifq")
fragments: org.bdgenomics.adam.rdd.fragment.FragmentRDD = RDDBoundFragmentRDD with 0 reference sequences, 0 read groups, and 0 processing steps

scala> fragments.rdd.first()
res0: org.bdgenomics.formats.avro.Fragment = {"readName": "NS500391:156:HV5LLBGX2:1:11101:25517:1050", "instrument": null, "runId": null, "fragmentSize": null, "alignments": [{"readInFragment": 0, "contigName": null, "start": null, "oldPosition": null, "end": null, "mapq": null, "readName": "NS500391:156:HV5LLBGX2:1:11101:25517:1050", "sequence": "TTTAANACACGAGGGTTAGCATCTCAGACCACCTGCTCTGCTCAGTTTGATTCCAGGGACTTGGTCTNATTNNNN", "qual": "AAAAA#EEEEEEE/EEEEEEEEEEEEE/EAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#EEE####", "cigar": null, "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": true, "properPair": false, "readMapped": false, "mateMapped": false, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": false, "mateNegativeStrand": f...
```

**Comment by heuermh** [comment]
I see, the problem looks to be when we're writing back out as interleaved FASTQ for the pipe to `bwa`, we must not be handling indexed sequences like the ones you are using correctly at that point.

**Comment by heuermh** [comment]
What version of Cannoli are you using?
I wonder if you have missed picking up the fix in https://github.com/bigdatagenomics/adam/pull/2081
