### ISSUE TITLE
How to use samtool commands 

### ISSUE THREAD

**Issue by Shekharrajak** [bigdatagenomics/cannoli#157]
Hello,

I am trying to run the samtool commands through cannoli, but didn't find any example or testcase related to it.

Commands, that I want to run through cannoli is : 

```
samtools view -Sb aligned.sam > aligned.bam

samtools sort aligned.bam aligned_sorted

samtools index aligned_sorted.bam

samtools tview aligned_sorted.bam ref.fa4


samtools mpileup -uf ref.fa aligned_sorted.bam | bcftools view -bvcg - > var.raw.bcf
bcftools view var.raw.bcf | vcfutils.pl varFilter -D100 > var.flt.vcf 

```

I tried to understand the codebase of cannoli for Samtool and see that code must be something like that : 

```

args = new SamtoolsMpileupArgs()
args.referencePath = // path of sam file from the BWA
args.addFiles = true // add all the referencePath files locally
val alignments = reads.callVariantsWithSamtoolsMpileup(args)

```

Can anyone please let me know, what is equivalent commands for above?

**Comment by Shekharrajak** [comment]
Ping @heuermh

**Comment by heuermh** [comment]
Hello @Shekharrajak!  Thank you for creating this issue.

Adding docs is something I need to get to soon (#91), meanwhile please let me try to explain here.

Very generally, Cannoli extends [ADAM](https://github.com/bigdatagenomics/adam), adapting the the ADAM [Pipe APIs](https://adam.readthedocs.io/en/latest/api/pipes/) with functions that wrap well-known bioinformatics tools.

Thus `samtools mpileup` can be seen as a function that transforms a dataset of alignments to a dataset of variants.  (And in fact, [it is](https://github.com/bigdatagenomics/cannoli/blob/master/core/src/main/scala/org/bdgenomics/cannoli/SamtoolsMpileup.scala#L70).)

None of the other commands you describe above need to pipe out to external tools, all those transformations can be done in ADAM on Apache Spark.

In `cannoli-shell`, something like the following
```
scala> import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.adam.rdd.ADAMContext._

scala> import org.bdgenomics.cannoli.Cannoli._
import org.bdgenomics.cannoli.Cannoli._

scala> val aligned = sc.loadAlignments("aligned.sam")
aligned: org.bdgenomics.adam.rdd.read.AlignmentRecordDataset =
RDDBoundAlignmentRecordDataset with 102 reference sequences, 1 read groups, and 2 processing steps

scala> val sorted = aligned.sortReadsByReferencePositionAndIndex()
sorted: org.bdgenomics.adam.rdd.read.AlignmentRecordDataset =
RDDBoundAlignmentRecordDataset with 102 reference sequences, 1 read groups, and 2 processing steps

scala> import org.bdgenomics.cannoli.SamtoolsMpileupArgs
import org.bdgenomics.cannoli.SamtoolsMpileupArgs

scala> val args = new SamtoolsMpileupArgs()
args: org.bdgenomics.cannoli.SamtoolsMpileupArgs = org.bdgenomics.cannoli.SamtoolsMpileupArgs@50da96f3

scala> args.referencePath = "/data/hs38DH.fa"
args.referencePath: String = /data/hs38DH.fa

scala> val variants = sorted.callVariantsWithSamtoolsMpileup(args)
variants: org.bdgenomics.adam.rdd.variant.VariantContextDataset =
RDDBoundVariantContextDataset with 102 reference sequences and 1 samples

scala> val filteredVariants = variants.transformDataset(dataset => dataset.filter(dataset.col("variant.annotation.readDepth") < 100))
filteredVariants: org.bdgenomics.adam.rdd.variant.VariantContextDataset =
DatasetBoundVariantContextDataset with 102 reference sequences and 1 samples

scala> filteredVariants.saveAsVcf("var.flt.vcf")
```


To go through your second example
```
args = new SamtoolsMpileupArgs()
args.referencePath = // path of sam file from the BWA
```

`args.referencePath` is the path to the genomic reference in FASTA format and its indexes if present.

One doesn't specify the path to the SAM file here.  Cannoli via Apache Spark will stream alignment records in BAM format over a pipe to `samtools` and receive variant context records in VCF format streamed back from `samtools`.

```
args.addFiles = true // add all the referencePath files locally
```

This argument is a bit complicated, depending on how your Apache Spark cluster is set up and whether you want to use Docker or Singularity.

By default `args.addFiles = false` the reference must be mounted at the same point on all the executor nodes in your cluster.  If this is not true, by specifying `args.addFiles = true` Cannoli can use the Apache Spark files mechanism to copy the reference to a temporary location on local disk on each executor node and use that path as the reference path.  For aligning against the human genome, this means copying 3G+ over the network to each of the executor nodes in your cluster before `samtools mpileup` is run.

```
val alignments = reads.callVariantsWithSamtoolsMpileup(args)
```

The result of `reads.callVariantsWithSamtoolsMpileup(args)` is a `VariantContextDataset`, so it would read better if this line were

```
val variants = reads.callVariantsWithSamtoolsMpileup(args)
```


Hope this helps!

**Comment by Shekharrajak** [comment]
I have few other queries : 

- How to run `bwa index ref.fa` using cannoli API ?
- How to run `bwa mem ref.fa reads.fastq > aligned.sam` ? I have done it using these lines : 

```
args.indexPath = "hs38dh"
args.sample = "sample"

val reads = sc.loadPairedFastqAsFragments(
"resources/bqsr1-r1.fq", "resources/bqsr1-r2.fq"
)
val alignments = reads.alignWithBwa(args)
alignments.saveAsParquet("sample.alignments.adam")

```
But I guess we can use fasta file instead of `fq` and load single file using `loadFastq` method, right? @heuermh . Please also let me know what is the difference between `loadFastqAsFragments` & `loadFastq` and if you have any sample ref.fa file for fast execution because I am trying `hs38dh.fa` file which is so large and takes a lot of time.

Thanks!

**Comment by heuermh** [comment]
`bwa index ref.fa` doesn't really fit the Cannoli model, as it isn't a transformation between one dataset and another.

For `bwa mem ref.fa reads.fastq > aligned.sam`, what you have looks correct for `cannoli-shell`.  Via the command line, it might look like

```bash
$ cannoli-submit \
  bwa \
  -index hs38dh \
  sample.ifq \
  sample.alignments.adam \
  sample
```

Note from the command line, the reads in FASTQ format must be in a single file, as interleaved FASTQ format.  Cannoli provides an `interleaveFastq` tool if you require it.

The ADAM method `loadFastq` loads files in FASTQ format as unaligned alignment records (similar to an unaligned BAM file (uBAM)).  `loadFastqAsFragments` returns fragments instead, which are pairs of unaligned reads.  It is basically the same as calling `loadFastq(sample.fq).toFragments()`.

I don't think `artificial.fa` is a proper reference genome for any of the reads used as test resources in ADAM.  You might want to grab reads from [Genome in a Bottle](https://jimb.stanford.edu/giab/) NA12878 and whichever [human reference genome reference](https://lh3.github.io/2017/11/13/which-human-reference-genome-to-use) you'd prefer.

**Comment by Shekharrajak** [comment]
Thanks @heuermh ! These discussions will be surely helpful for documenting this awesome tool. 

> For bwa mem ref.fa reads.fastq > aligned.sam, what you have looks correct for cannoli-shell. Via the command line, it might look like

Actually , I don't understand why 2 files will be passed in parameter. I just want to pass single fastq file , in this line : 

```
val reads = sc.loadPairedFastqAsFragments(
"resources/bqsr1-r1.fq", "resources/bqsr1-r2.fq"
)
```
So I tried this and got below error : 

```
var reads = sc.loadFastq("bqsr1-r2.fq").toFragments()
<console>:31: error: not enough arguments for method loadFastq: (pathName1: String, optPathName2: Option[String], optRecordGroup: Option[String], stringency: htsjdk.samtools.ValidationStringency)org.bdgenomics.adam.rdd.read.AlignmentRecordRDD.
Unspecified value parameter optPathName2.
       var reads = sc.loadFastq("bqsr1-r2.fq").toFragments()

```

Can you please let me know how can I get aligned SAM file for one `sample.fq`? (I tried `saveAsSam` but it says some error like it should be sorted).  My intention is to use this SAM file to sort and get filtered variants in VCF that syntax we have already discussed in [above comment](https://github.com/bigdatagenomics/cannoli/issues/157#issuecomment-473394903).

Currently I am downloading the hs37, hs38 from these URL : 

url38="ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_full_analysis_set.fna.gz"

url37d5="ftp://ftp.ncbi.nlm.nih.gov/1000genomes/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz"

But these files are really large (around 900 MB) so it takes a lot of time to check the output/method. So I was just looking for less size file (just simply asking. It is lower priority thing).

Thanks!

**Comment by Shekharrajak** [comment]
Ping @heuermh , any suggestion to load single fasta file and run bwa then save in sam file, so that I can follow your [suggested steps](https://github.com/bigdatagenomics/cannoli/issues/157#issuecomment-473394903) ? 

Thanks!

**Comment by heuermh** [comment]
There are two different types of sequence files necessary for alignment:

The first is the reference genome, in FASTA format.  To use bwa for aligning against this reference genome, you also need to create the bwa indexes.  This results in a whole bunch of files, e.g.
```
$ ls GCA*
GCA_000001405.25_GRCh38.p10_genomic.1.bt2
GCA_000001405.25_GRCh38.p10_genomic.1.ebwt
GCA_000001405.25_GRCh38.p10_genomic.2.bt2
GCA_000001405.25_GRCh38.p10_genomic.2.ebwt
GCA_000001405.25_GRCh38.p10_genomic.2bit
GCA_000001405.25_GRCh38.p10_genomic.3.bt2
GCA_000001405.25_GRCh38.p10_genomic.3.ebwt
GCA_000001405.25_GRCh38.p10_genomic.4.bt2
GCA_000001405.25_GRCh38.p10_genomic.4.ebwt
GCA_000001405.25_GRCh38.p10_genomic.fna
GCA_000001405.25_GRCh38.p10_genomic.fna.amb
GCA_000001405.25_GRCh38.p10_genomic.fna.ann
GCA_000001405.25_GRCh38.p10_genomic.fna.bwt
GCA_000001405.25_GRCh38.p10_genomic.fna.pac
GCA_000001405.25_GRCh38.p10_genomic.fna.sa
GCA_000001405.25_GRCh38.p10_genomic.rev.1.bt2
GCA_000001405.25_GRCh38.p10_genomic.rev.1.ebwt
GCA_000001405.25_GRCh38.p10_genomic.rev.2.bt2
GCA_000001405.25_GRCh38.p10_genomic.rev.2.ebwt
```

The second type of sequence file contains the short reads -- sequences and quality scores -- that come off the sequencing platform.  These are usually in FASTQ format, and paired end reads are usually split into separate files (sample_1.fq and sample_2.fq).

If you are using `cannoli-shell`, read these in using `sc.loadPairedFastqAsFragments("sample_1.fq", "sample_2.fq")`.

If you are using `cannoli-submit`, the two paired end read FASTQ files must be interleaved into a single FASTQ file.  There are multiple tools that can do this, including a command provided by `cannoli-submit`.

```
$ ./bin/cannoli-submit interleaveFastq --help
 INPUT1                 : First of pair reads in (possibly compressed) FASTQ
 INPUT2                 : Second of pair reads in (possibly compressed) FASTQ
 OUTPUT                 : Location to write interleaved FASTQ.
```

Hope this helps.

**Comment by Shekharrajak** [comment]
Thanks for letting me these points .

Yes, I have created the bwa index using `bwa index -p hs38 -a bwtsw -b 500000000 hs38.fa` and generated files are `hs38.amb  hs38.ann  hs38.bwt  hs38.fa  hs38.pac  hs38.sa `

now I am running this command 

`$ cannoli-submit bwa -index hs38 resources/bqsr1-r1.fq sample.alignments.adam sample`

But it is throwing this error : 

```
2019-03-26 15:49:43 WARN  Utils:66 - Your hostname, HackerDude resolves to a loopback address: 127.0.1.1; using 192.168.1.74 instead (on interface enp9s0)
2019-03-26 15:49:43 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
2019-03-26 15:49:43 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-03-26 15:49:43 INFO  Cannoli:93 - Cannoli invoked with args: "bwa" "-index" "hs38" "./resources/bqsr1-r1.fq" "sample.alignments.adam" "sample"
2019-03-26 15:49:43 INFO  SparkContext:54 - Running Spark version 2.4.0
2019-03-26 15:49:43 INFO  SparkContext:54 - Submitted application: bwa
2019-03-26 15:49:44 INFO  SecurityManager:54 - Changing view acls to: shekharrajak
2019-03-26 15:49:44 INFO  SecurityManager:54 - Changing modify acls to: shekharrajak
2019-03-26 15:49:44 INFO  SecurityManager:54 - Changing view acls groups to: 
2019-03-26 15:49:44 INFO  SecurityManager:54 - Changing modify acls groups to: 
2019-03-26 15:49:44 INFO  SecurityManager:54 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(shekharrajak); groups with view permissions: Set(); users  with modify permissions: Set(shekharrajak); groups with modify permissions: Set()
2019-03-26 15:49:44 INFO  Utils:54 - Successfully started service 'sparkDriver' on port 45099.
2019-03-26 15:49:44 INFO  SparkEnv:54 - Registering MapOutputTracker
2019-03-26 15:49:44 INFO  SparkEnv:54 - Registering BlockManagerMaster
2019-03-26 15:49:44 INFO  BlockManagerMasterEndpoint:54 - Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
2019-03-26 15:49:44 INFO  BlockManagerMasterEndpoint:54 - BlockManagerMasterEndpoint up
2019-03-26 15:49:44 INFO  DiskBlockManager:54 - Created local directory at /tmp/blockmgr-376f005d-982e-40a1-8c63-569516bf7e89
2019-03-26 15:49:44 INFO  MemoryStore:54 - MemoryStore started with capacity 366.3 MB
2019-03-26 15:49:44 INFO  SparkEnv:54 - Registering OutputCommitCoordinator
2019-03-26 15:49:44 INFO  log:192 - Logging initialized @1520ms
2019-03-26 15:49:44 INFO  Server:351 - jetty-9.3.z-SNAPSHOT, build timestamp: unknown, git hash: unknown
2019-03-26 15:49:44 INFO  Server:419 - Started @1590ms
2019-03-26 15:49:44 INFO  AbstractConnector:278 - Started ServerConnector@57dc9128{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2019-03-26 15:49:44 INFO  Utils:54 - Successfully started service 'SparkUI' on port 4040.
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@4a8b5227{/jobs,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@76b0ae1b{/jobs/json,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@130a0f66{/jobs/job,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@12365c88{/jobs/job/json,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6105f8a3{/stages,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@2237bada{/stages/json,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@77e2a6e2{/stages/stage,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6e0d4a8{/stages/stage/json,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@64d7b720{/stages/pool,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@30272916{/stages/pool/json,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5bb3d42d{/storage,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@5bf61e67{/storage/json,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@2c1dc8e{/storage/rdd,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@b273a59{/storage/rdd/json,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@4e7095ac{/environment,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@251ebf23{/environment/json,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@29b732a2{/executors,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@1b70203f{/executors/json,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@51671b08{/executors/threadDump,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@15051a0{/executors/threadDump/json,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@1162410a{/static,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@2472c7d8{/,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@589b028e{/api,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@3b0f7d9d{/jobs/job/kill,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@236ab296{/stages/stage/kill,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  SparkUI:54 - Bound SparkUI to 0.0.0.0, and started at http://192.168.1.74:4040
2019-03-26 15:49:44 INFO  SparkContext:54 - Added JAR file:/home/shekharrajak/Documents/ADAM/cannoli/bin/../assembly/target/cannoli-assembly-spark2_2.11-0.4.0-SNAPSHOT.jar at spark://192.168.1.74:45099/jars/cannoli-assembly-spark2_2.11-0.4.0-SNAPSHOT.jar with timestamp 1553595584576
2019-03-26 15:49:44 INFO  Executor:54 - Starting executor ID driver on host localhost
2019-03-26 15:49:44 INFO  Utils:54 - Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40815.
2019-03-26 15:49:44 INFO  NettyBlockTransferService:54 - Server created on 192.168.1.74:40815
2019-03-26 15:49:44 INFO  BlockManager:54 - Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
2019-03-26 15:49:44 INFO  BlockManagerMaster:54 - Registering BlockManager BlockManagerId(driver, 192.168.1.74, 40815, None)
2019-03-26 15:49:44 INFO  BlockManagerMasterEndpoint:54 - Registering block manager 192.168.1.74:40815 with 366.3 MB RAM, BlockManagerId(driver, 192.168.1.74, 40815, None)
2019-03-26 15:49:44 INFO  BlockManagerMaster:54 - Registered BlockManager BlockManagerId(driver, 192.168.1.74, 40815, None)
2019-03-26 15:49:44 INFO  BlockManager:54 - Initialized BlockManager: BlockManagerId(driver, 192.168.1.74, 40815, None)
2019-03-26 15:49:44 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@72fe8a4f{/metrics/json,null,AVAILABLE,@Spark}
2019-03-26 15:49:44 INFO  ADAMContext:3349 - Loading ./resources/bqsr1-r1.fq as Parquet containing Fragments.
Command body threw exception:
java.io.FileNotFoundException: Couldn't find any files matching resources/bqsr1-r1.fq for the requested PathFilter
2019-03-26 15:49:45 INFO  Bwa:44 - Overall Duration: 1.21 secs
Exception in thread "main" java.io.FileNotFoundException: Couldn't find any files matching resources/bqsr1-r1.fq for the requested PathFilter
	at org.bdgenomics.adam.rdd.ADAMContext.getFsAndFilesWithFilter(ADAMContext.scala:1428)
	at org.bdgenomics.adam.rdd.ADAMContext.loadAvroSequenceDictionary(ADAMContext.scala:1226)
	at org.bdgenomics.adam.rdd.ADAMContext.loadParquetFragments(ADAMContext.scala:2949)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadFragments$1.apply(ADAMContext.scala:3350)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadFragments$1.apply(ADAMContext.scala:3328)
	at scala.Option.fold(Option.scala:158)
	at org.apache.spark.rdd.Timer.time(Timer.scala:48)
	at org.bdgenomics.adam.rdd.ADAMContext.loadFragments(ADAMContext.scala:3328)
	at org.bdgenomics.cannoli.cli.Bwa.run(Bwa.scala:97)
	at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:55)
	at org.bdgenomics.cannoli.cli.Bwa.run(Bwa.scala:83)
	at org.bdgenomics.cannoli.cli.Cannoli.apply(Cannoli.scala:110)
	at org.bdgenomics.cannoli.cli.Cannoli$.main(Cannoli.scala:46)
	at org.bdgenomics.cannoli.cli.Cannoli.main(Cannoli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2019-03-26 15:49:45 INFO  SparkContext:54 - Invoking stop() from shutdown hook
2019-03-26 15:49:45 INFO  AbstractConnector:318 - Stopped Spark@57dc9128{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2019-03-26 15:49:45 INFO  SparkUI:54 - Stopped Spark web UI at http://192.168.1.74:4040
2019-03-26 15:49:45 INFO  MapOutputTrackerMasterEndpoint:54 - MapOutputTrackerMasterEndpoint stopped!
2019-03-26 15:49:45 INFO  MemoryStore:54 - MemoryStore cleared
2019-03-26 15:49:45 INFO  BlockManager:54 - BlockManager stopped
2019-03-26 15:49:45 INFO  BlockManagerMaster:54 - BlockManagerMaster stopped
2019-03-26 15:49:45 INFO  OutputCommitCoordinator$OutputCommitCoordinatorEndpoint:54 - OutputCommitCoordinator stopped!
2019-03-26 15:49:45 INFO  SparkContext:54 - Successfully stopped SparkContext
2019-03-26 15:49:45 INFO  ShutdownHookManager:54 - Shutdown hook called
2019-03-26 15:49:45 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-145f7447-9137-438b-91d3-81103e88caeb
2019-03-26 15:49:45 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-3efac57a-18be-44b0-b64d-0db3532eb047
```

Even I tried with full path of the fq file and I am sure that file is present in the path.

**Comment by heuermh** [comment]
Sorry, it appears that you've run into a not very useful error message.  This line in the log explains what is happening
```
ADAMContext:3349 - Loading ./resources/bqsr1-r1.fq as Parquet containing Fragments.
```

`./resources/bqsr1-r1.fq` is clearly not a directory of Parquet files containing Fragments.  File extension guessing has failed us here

https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L3348

https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/FileExtensions.scala#L90

ADAM expects `.ifq` for interleaved FASTQ format, so renaming your file `resources/bqsr1-r1.ifq` or calling `loadInterleavedFastqAsFragments` instead of `loadFragments` would work.

**Comment by heuermh** [comment]
Closing as resolved -- please reopen this issue if you would like.
