### ISSUE TITLE
Read issue - Parquet/Avro schema mismatch

### ISSUE THREAD

**Issue by benraha** [bigdatagenomics/cannoli#176]
Hi,

While using ADAM 0.28.0 (from tar.gz) to transformAlignments and Cannoli 0.6 to run Bowtie2 on, I got the following error :

~~~~
Exception in thread "main" org.apache.spark.SparkException: Job aborted.
	at org.apache.spark.internal.io.SparkHadoopWriter$.write(SparkHadoopWriter.scala:100)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1083)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:1081)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:1081)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:1081)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply$mcV$sp(PairRDDFunctions.scala:1000)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:991)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:991)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:991)
	at org.bdgenomics.adam.rdd.AvroGenomicDataset$$anonfun$saveRddAsParquet$1.apply$mcV$sp(GenomicDataset.scala:3816)
	at org.bdgenomics.adam.rdd.AvroGenomicDataset$$anonfun$saveRddAsParquet$1.apply(GenomicDataset.scala:3800)
	at org.bdgenomics.adam.rdd.AvroGenomicDataset$$anonfun$saveRddAsParquet$1.apply(GenomicDataset.scala:3800)
	at scala.Option.fold(Option.scala:158)
	at org.apache.spark.rdd.Timer.time(Timer.scala:48)
	at org.bdgenomics.adam.rdd.AvroGenomicDataset.saveRddAsParquet(GenomicDataset.scala:3800)
	at org.bdgenomics.adam.rdd.AvroGenomicDataset.saveAsParquet(GenomicDataset.scala:3882)
	at org.bdgenomics.adam.rdd.GenomicDataset$class.saveAsParquet(GenomicDataset.scala:322)
	at org.bdgenomics.adam.rdd.AvroGenomicDataset.saveAsParquet(GenomicDataset.scala:3771)
	at org.bdgenomics.adam.rdd.read.AlignmentRecordDataset.save(AlignmentRecordDataset.scala:605)
	at org.bdgenomics.cannoli.cli.Bowtie2.run(Bowtie2.scala:74)
	at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:55)
	at org.bdgenomics.cannoli.cli.Bowtie2.run(Bowtie2.scala:67)
	at org.bdgenomics.cannoli.cli.Cannoli.apply(Cannoli.scala:111)
	at org.bdgenomics.cannoli.cli.Cannoli$.main(Cannoli.scala:47)
	at org.bdgenomics.cannoli.cli.Cannoli.main(Cannoli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, 192.168.128.4, executor 0): org.apache.parquet.io.InvalidRecordException: Parquet/Avro schema mismatch. Avro field 'referenceName' not found.
	at org.apache.parquet.avro.AvroIndexedRecordConverter.getAvroField(AvroIndexedRecordConverter.java:135)
	at org.apache.parquet.avro.AvroIndexedRecordConverter.<init>(AvroIndexedRecordConverter.java:91)
	at org.apache.parquet.avro.AvroIndexedRecordConverter.<init>(AvroIndexedRecordConverter.java:66)
	at org.apache.parquet.avro.AvroCompatRecordMaterializer.<init>(AvroCompatRecordMaterializer.java:34)
	at org.apache.parquet.avro.AvroReadSupport.newCompatMaterializer(AvroReadSupport.java:144)
	at org.apache.parquet.avro.AvroReadSupport.prepareForRead(AvroReadSupport.java:136)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:204)
	at org.apache.parquet.hadoop.ParquetRecordReader.initializeInternalReader(ParquetRecordReader.java:182)
	at org.apache.parquet.hadoop.ParquetRecordReader.initialize(ParquetRecordReader.java:140)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.liftedTree1$1(NewHadoopRDD.scala:199)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:196)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:151)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:70)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
~~~~ 

This happened with Cannoli 0.6.0, 0.5.0, and the current master version as well. When I open the alignment file with PySpark, I can see that this field indeed exists, although contains only nulls. Opening the file with ADAM (countKmers) worked.

I run the process using :
bash cannoli-submit bowtie2 -executable /bowtie2/bowtie2-2.3.5.1-linux-x86_64/bowtie2 -index /hg19 <input> <output>

The input process was a fastq file -> transformAlignments -> Cannoli.

Help will be greatly appreciated,
Ben

**Comment by heuermh** [comment]
Hello @benraha, thank you for submitting this issue.

To clarify, you're doing something like this?
```
$ adam-submit transformAlignments -paired_fq sample_2.fq sample_1.fq sample.alignments.adam
$ cannoli-submit bowtie2 ... sample.alignments.adam
```

It may be that we have a incomplete or unclear documentation problem, at least with the command line interface for Cannoli.

From an API point of view (and when using the Scala shell) it might be more clear that `bowtie2` is a transformation function that goes from `FragmentDataset` to `AlignmentRecordDataset`.
```scala
class Bowtie2(val args: Bowtie2Args, sc: SparkContext)
  extends CannoliFn[FragmentDataset, AlignmentRecordDataset](sc) with Logging {

  override def apply(fragments: FragmentDataset): AlignmentRecordDataset = { ... }
```

A `Fragment` in our schema is defined as the DNA fragment that was targeted by the sequencer, resulting in one or more reads.  Most often this encapsulates the two paired reads in paired end read sequencing.  A `FragmentDataset` can be created from one file in interleaved FASTQ format, two files of paired reads in FASTQ format, or from any of the alignment formats (SAM/BAM/CRAM) by calling `AlignmentDataset.toFragments()`.

The `bowtie2` command line operation in Cannoli accepts one file in interleaved FASTQ format or a Parquet directory of `Fragment`s as `INPUT`.  Is the error you are seeing because the Parquet directory is `AlignmentRecord`s instead of `Fragment`s?

If so, then instead of the `transformAlignments` call you can use the `interleaveFastq` Cannoli command line operation to get a Parquet directory of `Fragment`s
```bash
$ cannoli-submit interleaveFastq sample_1.fq sample_2.fq sample.fragments.adam
```

or something like the following in `adam-shell` or `cannoli-shell`

```scala
import org.bdgenomics.adam.rdd.ADAMContext._
val alignments = sc.loadAlignments(...) // FASTQ, SAM/BAM/CRAM, etc.
val fragments = alignments.toFragments()
fragments.saveAsParquet("sample.fragments.adam")
```


Or all that said it could be that I messed something up when cutting all the releases around the ADAM 0.28.0 release; there are several repos that need to be released before an ADAM release and several others that go after an ADAM release, and it is sometimes difficult to coordinate the whole lot.

**Comment by benraha** [comment]
Hi,

Thanks for the quick response :)

This was indeed the problem - I misunderstood that, and once I changed to write Fragments, everything worked as expected.

Maybe adding it in a more clear way in the documentation can help others not run into this, although now I notice that it does say **pipe fragments** in the input documentation of Bowtie2.

Thanks!
Ben

**Comment by heuermh** [comment]
> Maybe adding it in a more clear way in the documentation can help others not run into this

Yes, sadly I haven't found time to get to https://github.com/bigdatagenomics/cannoli/issues/91 or to write up a Cannoli manuscript yet . . . perhaps after the BOSC conference this month
