### ISSUE TITLE
Cannoli fails on missing Bowtie2 index file unnecessarily

### ISSUE THREAD

**Issue by benraha** [bigdatagenomics/cannoli#177]
Running Bowtie2 with an index file has a weird convention, that the index file name sent (via the -x parameter) does not exist, but rather files with the same name and with an extension (a basename).

As mentioned here : http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml: "The basename of the index for the reference genome. The basename is the name of any of the index files up to but not including the final .1.bt2 / .rev.1.bt2 / etc. "

While running Cannoli like that :
cannoli-submit bowtie2 -executable bowtie2 -index "/bowtie/index/hg19/hg19" <input> <output> ...

I get the following error :
~~~~

java.io.FileNotFoundException: File /bowtie/index/hg19/hg19 does not exist
19/07/16 13:43:35 INFO Bowtie2: Overall Duration: 3.83 secs
Exception in thread "main" java.io.FileNotFoundException: File /bowtie/index/hg19/hg19 does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:611)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:824)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:601)
	at org.apache.hadoop.fs.FileSystem.resolvePath(FileSystem.java:753)
	at org.apache.hadoop.fs.FilterFileSystem.resolvePath(FilterFileSystem.java:152)
	at org.bdgenomics.cannoli.CannoliFn.absolute(CannoliFn.scala:42)
	at org.bdgenomics.cannoli.Bowtie2.apply(Bowtie2.scala:74)
	at org.bdgenomics.cannoli.cli.Bowtie2.run(Bowtie2.scala:73)
	at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:55)
	at org.bdgenomics.cannoli.cli.Bowtie2.run(Bowtie2.scala:67)
	at org.bdgenomics.cannoli.cli.Cannoli.apply(Cannoli.scala:112)
	at org.bdgenomics.cannoli.cli.Cannoli$.main(Cannoli.scala:48)
	at org.bdgenomics.cannoli.cli.Cannoli.main(Cannoli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
~~~~

This file existence check shouldn't happen since this exact file name indeed does not exist.

**A workaround** is to create this filename, which Bowtie2 ignores, and everything works as expected.

Thanks in advance,
Ben

**Comment by heuermh** [comment]
Thank you for submitting this issue, @benraha!

I've never run into this because the `ref.fa` basename file is always present in the same directory as the bowtie2 indexes, but clearly this will not always be the case.

Unfortunately I've had a good look at this, and because we have to support a bunch of different use cases (indexes on local file system on every executor node, indexes on shared file system, indexes on local file system on the driver node copied to executor nodes via SparkFiles mechanism, and mounting to Docker and Singularity volumes for all of the above), I can't find a way to let a non-existent basename path work its way all the way through.

I could add a fail-fast to Bowtie2 and other commands that reference an index basename in a similar manner, with an error message `Basename of the index %s not found, touch an empty file at this path if it does not exist`.  What do you think?

**Comment by benraha** [comment]
Hi!

I think that adding the error message should suffice, as fixing that seems not straight forward and adding an empty file does not cause any harm (and let's face it - this is an odd behaviour from the bowtie2 side to reference a non-exiting file).

Ben

**Comment by heuermh** [comment]
@benraha Please let me know if #181 works for you as a workaround.
