### ISSUE TITLE
IllegalArgumentException: Reference index for 'chr3' not found in sequence dictionary

### ISSUE THREAD

**Issue by Arun-George-Zachariah** [bigdatagenomics/cannoli#236]
Hi, 

While performing variant analysis with cannoli, using Freebayes, I get the following error.
```
java.lang.IllegalArgumentException: Reference index for 'chr3' not found in sequence dictionary.
	at htsjdk.samtools.SAMRecord.resolveIndexFromName(SAMRecord.java:540)
	at htsjdk.samtools.SAMRecord.setHeaderStrict(SAMRecord.java:1668)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:180)
	at org.bdgenomics.adam.rdd.read.AnySAMInFormatter$$anonfun$write$1.apply(AnySAMInFormatter.scala:97)
	at org.bdgenomics.adam.rdd.read.AnySAMInFormatter$$anonfun$write$1.apply(AnySAMInFormatter.scala:95)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.bdgenomics.adam.rdd.read.AnySAMInFormatter$class.write(AnySAMInFormatter.scala:95)
	at org.bdgenomics.adam.rdd.read.BAMInFormatter.write(BAMInFormatter.scala:41)
	at org.bdgenomics.adam.rdd.InFormatterRunner.run(InFormatter.scala:27)
	at java.lang.Thread.run(Thread.java:748)
```
	
The index files of the reference genome created using `bwa` are:
```
hs38.fa.amb  
hs38.fa.ann  
hs38.fa.bwt  
hs38.fa.dict  
hs38.fa.pac 
hs38.fa.sa
```

The index file using `samtools` `faidx`:
`hs38.fa.fai`
	
The code used:

```
val freebayesArgs = new FreebayesArgs()
freebayesArgs.referencePath = "file:///Ref_Data/hs38.fa"
freebayesArgs.addFiles = true
freebayesArgs.executable = "/path/to/freebayes/bin/freebayes"

val variantContexts = markdup.callVariantsWithFreebayes(freebayesArgs)

variantContexts.saveAsVcf("output.freebayes.vcf.bgz")
```

What could be the reason for this error?

**Comment by heuermh** [comment]
Hello @Arun-George-Zachariah!

A couple of questions:  is `chr3` present in `hs38.fa`?
What about in the sequence dictionary for the BAM file (i.e. `markdup` in your example code)?

**Comment by Arun-George-Zachariah** [comment]
> A couple of questions: is `chr3` present in `hs38.fa`?

Yes. 

`>chr3  AC:CM000665.2  gi:568336021  LN:198295559  rl:Chromosome  M5:76635a41ea913a405ded820447d067b0  AS:GRCh38`

> What about in the sequence dictionary for the BAM file (i.e. `markdup` in your example code)?

I had saved the contents of `markdup` as a sam file. It too has `chr3`. Is there any other way, you would like me to view the contents?

**Comment by heuermh** [comment]
Hmm, mismatch between the reference used for alignment (sequence dictionary in the BAM file) and reference used for variant calling is typically when this kind of error shows up.

Are you running Spark in cluster mode?

**Comment by Arun-George-Zachariah** [comment]
True. And, yes. It is being executed on an 8 node spark cluster.

**Comment by heuermh** [comment]
Thanks for the clarification, I will try to replicate this error on AWS EMR this week.

**Comment by Arun-George-Zachariah** [comment]
Thanks. The issue here is mainly because the sequence dictionary was empty. I was performing alignments on the reads using `sortByReferencePosition`. It does not raise an error, that led me to believe that everything was right.`sortByReferencePositionAndIndex` however, threw an error pointed out with #237.

I am now able to save the output as parquet with `variantContexts.toVariants.saveAsParquet`. But I get the below error while trying to save it as `vcf`.

```
java.io.FileNotFoundException: File output.freebayes.vcf.bgz_head does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:611)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:824)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:601)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:421)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:142)
	at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:346)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:769)
	at org.seqdoop.hadoop_bam.util.WrapSeekable.openPath(WrapSeekable.java:60)
	at org.seqdoop.hadoop_bam.KeyIgnoringVCFOutputFormat.readHeaderFrom(KeyIgnoringVCFOutputFormat.java:82)
	at org.bdgenomics.adam.rdd.variant.ADAMVCFOutputFormat.getRecordWriter(ADAMVCFOutputFormat.scala:45)
```

**Comment by heuermh** [comment]
Sorry, is the `FileNotFoundException` in the last comment still an issue?  You may wish to try building off #273, which improves VCF writing from `freebayes`.

**Comment by Arun-George-Zachariah** [comment]
Hi @heuermh, thanks for the follow-up. This is no longer an issue, with the latest push.

Closing the issue.
