### ISSUE TITLE
Exception encountered while loading parquet files generated using Cannoli CLI.

### ISSUE THREAD

**Issue by Arun-George-Zachariah** [bigdatagenomics/cannoli#258]
Hi, 

I get the below error, after I try to load the parquet file, obtained after calling variants with freebayes, from the Cannoli CLI. 

```
org.apache.parquet.io.InvalidRecordException: Parquet/Avro schema mismatch. Avro field 'variant' not found.
	at org.apache.parquet.avro.AvroIndexedRecordConverter.getAvroField(AvroIndexedRecordConverter.java:135)
	at org.apache.parquet.avro.AvroIndexedRecordConverter.<init>(AvroIndexedRecordConverter.java:91)
	at org.apache.parquet.avro.AvroIndexedRecordConverter.<init>(AvroIndexedRecordConverter.java:66)
	at org.apache.parquet.avro.AvroCompatRecordMaterializer.<init>(AvroCompatRecordMaterializer.java:34)
	at org.apache.parquet.avro.AvroReadSupport.newCompatMaterializer(AvroReadSupport.java:144)
	at org.apache.parquet.avro.AvroReadSupport.prepareForRead(AvroReadSupport.java:136)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:204)
	at org.apache.parquet.hadoop.ParquetRecordReader.initializeInternalReader(ParquetRecordReader.java:182)
	at org.apache.parquet.hadoop.ParquetRecordReader.initialize(ParquetRecordReader.java:140)
```
	
How do I go about this issue?

**Comment by Arun-George-Zachariah** [comment]
Looks like the CLI code has some missing components, that prevent loading the parquet file and hence the issue. The fix for this is done as a part of the pull request #259.

**Comment by heuermh** [comment]
Hello @Arun-George-Zachariah, thank you for submitting this issue!

How are you reading in the Parquet file created by `Freebayes`?  The most efficient route would be `loadParquetVariantContexts`

**Comment by Arun-George-Zachariah** [comment]
Hi @heuermh,

Yes. I am trying to read the parquet files, created by Freebayes. `loadParquetVariantContexts` works perfectly fine.

Thanks for the clarification!
