### ISSUE TITLE
BwaArgs is not a member of package org.bdgenomics.cannoli

### ISSUE THREAD

**Issue by tahashmi** [bigdatagenomics/cannoli#274]
Hi,

I have build both ADAM and Cannoli on my system. Shell CLI for both is working. But when I export following commands: 

```
~/ogits/cannoli$ /home/tahmad/ogits/cannoli/bin/cannoli-shell --driver-memory 2G --executor-memory 2G
Using SPARK_SHELL=/opt/spark/bin/spark-shell
20/10/24 19:19:02 WARN Utils: Your hostname, TUD256255 resolves to a loopback address: 127.0.1.1; using 192.168.1.66 instead (on interface wlp2s0)
20/10/24 19:19:02 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
20/10/24 19:19:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://192.168.1.66:4040
Spark context available as 'sc' (master = local[*], app id = local-1603559949542).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.0
      /_/
         
Using Scala version 2.12.10 (OpenJDK 64-Bit Server VM, Java 11.0.8)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.adam.rdd.ADAMContext._

scala> import org.bdgenomics.cannoli.Cannoli._
import org.bdgenomics.cannoli.Cannoli._

scala> import org.bdgenomics.cannoli.BwaArgs
<console>:29: error: object BwaArgs is not a member of package org.bdgenomics.cannoli
       import org.bdgenomics.cannoli.BwaArgs
              ^

scala>
```
object BwaArgs is not a member of package org.bdgenomics.cannoli occurs.

**Comment by heuermh** [comment]
Hello @tahashmi!

In a recently merged pull request https://github.com/bigdatagenomics/cannoli/pull/264, the `Bwa*` classes were renamed to `BwaMem*` to be consistent with newly added support for `BwaMem2` (pull request https://github.com/bigdatagenomics/cannoli/pull/256).

Hope this helps!

**Comment by tahashmi** [comment]
Hi @heuermh , Thanks!

Can you please also help in setting next parameters?

```
scala> val args = new BwaArgs()
<console>:27: error: not found: type BwaArgs
       val args = new BwaArgs()
                      ^

scala> val args = new BwaMem()
<console>:27: error: not enough arguments for constructor BwaMem: (args: org.bdgenomics.cannoli.BwaMemArgs, sc: org.apache.spark.SparkContext)org.bdgenomics.cannoli.BwaMem.
Unspecified value parameters args, sc.
       val args = new BwaMem()
                  ^

scala> val args = new BwaMem(org.bdgenomics.cannoli.BwaMem, org.apache.spark.SparkContext)
<console>:27: error: object BwaMem is not a member of package org.bdgenomics.cannoli
Note: class BwaMem exists, but it has no companion object.
       val args = new BwaMem(org.bdgenomics.cannoli.BwaMem, org.apache.spark.SparkContext)
                                                    ^
<console>:27: error: type mismatch;
 found   : org.apache.spark.SparkContext.type
 required: org.apache.spark.SparkContext
       val args = new BwaMem(org.bdgenomics.cannoli.BwaMem, org.apache.spark.SparkContext)
                                                                             ^

scala> 
```

**Comment by heuermh** [comment]
This works for me

```scala
$ ./bin/cannoli-shell
...

scala> import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.adam.rdd.ADAMContext._

scala> import org.bdgenomics.cannoli.Cannoli._
import org.bdgenomics.cannoli.Cannoli._

scala> import org.bdgenomics.cannoli.BwaMemArgs
import org.bdgenomics.cannoli.BwaMemArgs

scala> val reads = sc.loadPairedFastqAsFragments("sample_1.fq", "sample_2.fq")
reads: org.bdgenomics.adam.rdd.fragment.FragmentDataset = RDDBoundFragmentDataset with 0 reference sequences, 0 read groups, and 0 processing steps

scala> val args = new BwaMemArgs()
args: org.bdgenomics.cannoli.BwaMemArgs = org.bdgenomics.cannoli.BwaMemArgs@5af75e60

scala> args.sampleId = "sample"
args.sampleId: String = sample

scala> args.indexPath = "ref.fa"
args.indexPath: String = ref.fa

scala> reads.alignWithBwaMem(args)
res0: org.bdgenomics.adam.rdd.read.AlignmentDataset = RDDBoundAlignmentDataset with 0 reference sequences, 1 read groups, and 0 processing steps
```

Note in `cannoli-shell` you can use the tab key to help tab-complete per the API, e.g.
```
scala> args.[press tab key]
addFiles          executable   indexPath     platform        predictedMedianInsertSize   runDate            sudo
createReadGroup   flowOrder    keySequence   platformModel   readGroup                   sampleId           useDocker
doPrintUsage      image        library       platformUnit    readGroupId                 sequencingCenter   useSingularity
```

Hope this helps!

**Comment by tahashmi** [comment]
Hi @heuermh . Thanks. But still I am not lucky to run BWA, even I set the BWA path.

```
scala> args.executable="/home/tahmad/ogits/cannoli/bin/bwa"
args.executable: String = /home/tahmad/ogits/cannoli/bin/bwa

scala> alignments.saveAsParquet("sample.alignments.adam")
20/10/26 00:51:45 ERROR Executor: Exception in task 0.0 in stage 17.0 (TID 18)
java.io.IOException: Cannot run program "bwa": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.bdgenomics.adam.rdd.GenomicDataset.$anonfun$pipe$8(GenomicDataset.scala:859)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 18 more
20/10/26 00:51:45 ERROR Executor: Exception in task 1.0 in stage 17.0 (TID 19)
java.io.IOException: Cannot run program "bwa": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.bdgenomics.adam.rdd.GenomicDataset.$anonfun$pipe$8(GenomicDataset.scala:859)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: error=2, No such file or directory

```

**Comment by heuermh** [comment]
The bwa path should show up in a few places in the logs, e.g.
```
$ cannoli-submit bwaMem \
  -executable "/usr/local/bin/bwa" \
  -index /data/Homo_sapiens_assembly19.fasta \
  -sample_id NA12878 \
  CEUTrio.HiSeq.WGS.b37.NA12878.20.21.tiny.unaligned.bam \
  CEUTrio.HiSeq.WGS.b37.NA12878.20.21.tiny.unaligned.bwa.alignments.adam
...
20/10/28 08:08:47 INFO BwaMem: Piping RDDBoundFragmentDataset with 0 reference sequences,
1 read groups, and 0 processing steps to bwa with command: [/usr/local/bin/bwa, mem, -t, 1, -R,
@RG\tID:NA12878\tSM:NA12878\tLB:NA12878\tPL:ILLUMINA\tPU:0, -p,
/data/Homo_sapiens_assembly19.fasta, -] files: []
...
[main] CMD: /usr/local/bin/bwa mem -t 1 -R @RG\tID:NA12878\tSM:NA12878\tLB:NA12878\t
PL:ILLUMINA\tPU:0 -p /data/Homo_sapiens_assembly19.fasta -
```

In `cannoli-shell`
```scala
$ ./bin/cannoli-shell

scala> import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.adam.rdd.ADAMContext._

scala> import org.bdgenomics.cannoli.Cannoli._
import org.bdgenomics.cannoli.Cannoli._

scala> import org.bdgenomics.cannoli.BwaMemArgs
import org.bdgenomics.cannoli.BwaMemArgs

scala> val reads = sc.loadFragments("/data/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.tiny.unaligned.bam")
reads: org.bdgenomics.adam.rdd.fragment.FragmentDataset = RDDBoundFragmentDataset with
0 reference sequences, 1 read groups, and 0 processing steps

scala> val args = new BwaMemArgs()
args: org.bdgenomics.cannoli.BwaMemArgs = org.bdgenomics.cannoli.BwaMemArgs@6114fc0f

scala> args.sampleId = "NA12878"
args.sampleId: String = NA12878

scala> args.indexPath = "/data/Homo_sapiens_assembly19.fasta"
args.indexPath: String = /data/Homo_sapiens_assembly19.fasta

scala> args.executable = "/usr/local/bin/bwa"
args.executable: String = /usr/local/bin/bwa

scala> val alignments = reads.alignWithBwaMem(args)
alignments: org.bdgenomics.adam.rdd.read.AlignmentDataset = RDDBoundAlignmentDataset with
0 reference sequences, 1 read groups, and 0 processing steps

scala> alignments.saveAsParquet("/data/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.tiny.unaligned.bwa.alignments.adam")
...
[main] CMD: /usr/local/bin/bwa mem -t 1 -R @RG\tID:NA12878\tSM:NA12878\tLB:NA12878\tPL:ILLUMINA\tPU:0
-p /data/Homo_sapiens_assembly19.fasta -
```

Note that if you are running on a cluster, the executable path must be valid on all of the executor nodes, in other words, `bwa` would need to be installed to the same path on every executor node.

**Comment by tahashmi** [comment]
Thanks @heuermh , I am able to run BWA. 

I have loaded `sample.alignments.adam` alignments below but `sortByReferencePositionAndIndex()` is throwing some `UnsupportedOperationException` error. While `sortByReferencePosition()` is working with these alignments. 

```
val alignments = sc.loadAlignments("/home/tahmad/tahmad/bd/cannoli/sample.alignments.adam")
scala> val sorted = alignments.
!=                                          countKmersAsDataset          isInstanceOf                               rightOuterBroadcastRegionJoin                         spark                         
##                                          dataset                      isSorted                                   rightOuterBroadcastRegionJoinAgainst                  synchronized                  
+                                           ensuring                     jrdd                                       rightOuterBroadcastRegionJoinAgainstAndGroupByRight   toCoverage                    
->                                          eq                           leftNormalizeIndels                        rightOuterBroadcastRegionJoinAndGroupByRight          toDF                          
==                                          equals                       leftOuterShuffleRegionJoin                 rightOuterShuffleRegionJoin                           toFragments                   
addProcessingStep                           filterByMappingQuality       leftOuterShuffleRegionJoinAndGroupByLeft   rightOuterShuffleRegionJoinAndGroupByLeft             toReads                       
addReadGroup                                filterByOverlappingRegion    markDuplicates                             save                                                  toString                      
addReadGroups                               filterByOverlappingRegions   ne                                         saveAsFastq                                           transform                     
addSequence                                 filterDuplicateReads         notify                                     saveAsPairedFastq                                     transformDataFrame            
addSequences                                filterToPrimaryAlignments    notifyAll                                  saveAsParquet                                         transformDataset              
asInstanceOf                                filterToReadGroup            persist                                    saveAsPartitionedParquet                              transmute                     
binQualityScores                            filterToReadGroups           pipe                                       saveAsSam                                             transmuteDataFrame            
broadcast                                   filterToSample               processingSteps                            saveAsSamString                                       transmuteDataset              
broadcastRegionJoin                         filterToSamples              rdd                                        sequences                                             uTag                          
broadcastRegionJoinAgainst                  filterUnalignedReads         readGroups                                 shuffleRegionJoin                                     union                         
broadcastRegionJoinAgainstAndGroupByRight   filterUnpairedReads          realignIndels                              shuffleRegionJoinAndGroupByLeft                       unpersist                     
broadcastRegionJoinAndGroupByRight          flagStat                     reassembleReadPairs                        sort                                                  wait                          
cache                                       formatted                    recalibrateBaseQualities                   sortByReadName                                        writePartitionedParquetFlag   
computeMismatchingPositions                 fullOuterShuffleRegionJoin   replaceProcessingSteps                     sortByReferencePosition                               →                             
convertToSam                                getClass                     replaceReadGroups                          sortByReferencePositionAndIndex                                                     
countKmers                                  hashCode                     replaceSequences                           sortLexicographically                                                               

scala> val sorted = alignments.sortByReferencePositionAndIndex()
java.lang.UnsupportedOperationException: empty.max
  at scala.collection.TraversableOnce.max(TraversableOnce.scala:234)
  at scala.collection.TraversableOnce.max$(TraversableOnce.scala:232)
  at scala.collection.AbstractTraversable.max(Traversable.scala:108)
  at org.bdgenomics.adam.rdd.read.AlignmentDataset.sortByReferencePositionAndIndex(AlignmentDataset.scala:1032)
  ... 49 elided

scala> 
```

**Comment by heuermh** [comment]
Hello @tahashmi!

If you ran BWA starting from FASTQ files, you will need to set the sequence dictionary on the result if you want to sort by reference position and index.

E.g.
```scala
val alignments = sc.loadAlignments("/home/tahmad/tahmad/bd/cannoli/sample.alignments.adam")
val sequences = sc.loadSequenceDictionary("reference.dict")
val withSequences = alignments.replaceSequences(sequences)
val sorted = withSequences.sortByReferencePositionAndIndex()
```

https://javadoc.io/static/org.bdgenomics.adam/adam-core-spark3_2.12/0.32.0/org/bdgenomics/adam/rdd/ADAMContext.html#loadSequenceDictionary(pathName:String):org.bdgenomics.adam.models.SequenceDictionary

See also https://github.com/bigdatagenomics/cannoli/issues/237#issuecomment-620722795  As that mentions, doc & error messages for this should be improved
