### ISSUE TITLE
NoSuchMethodError when running cannoli locally

### ISSUE THREAD

**Issue by gunjanbaid** [bigdatagenomics/cannoli#45]
I am working on adding MACS2 to cannoli. When running cannoli locally, I get the following error:

```
$ ADAM_MAIN=org.bdgenomics.cannoli.Cannoli \
    adam-submit \
    --jars target/cannoli-spark2_2.11-0.1-SNAPSHOT.jar \
    -- \
    macs2 -t test.bed

Using ADAM_MAIN=org.bdgenomics.cannoli.Cannoli
Using SPARK_SUBMIT=/Applications/spark-2.1.1-bin-hadoop2.7/bin/spark-submit
2017-06-30 12:44:28 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Command body threw exception:
java.lang.NoSuchMethodError: org.bdgenomics.adam.rdd.ADAMContext.loadFeatures(Ljava/lang/String;Lscala/Option;Lscala/Option;Lscala/Option;)Lorg/bdgenomics/adam/rdd/feature/FeatureRDD;
Exception in thread "main" java.lang.NoSuchMethodError: org.bdgenomics.adam.rdd.ADAMContext.loadFeatures(Ljava/lang/String;Lscala/Option;Lscala/Option;Lscala/Option;)Lorg/bdgenomics/adam/rdd/feature/FeatureRDD;
	at org.bdgenomics.cannoli.Macs2.run(Macs2.scala:111)
	at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:55)
	at org.bdgenomics.cannoli.Macs2.run(Macs2.scala:94)
	at org.bdgenomics.adam.cli.ADAMMain.apply(ADAMMain.scala:126)
	at org.bdgenomics.cannoli.Cannoli$.main(Cannoli.scala:36)
	at org.bdgenomics.cannoli.Cannoli.main(Cannoli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

I was working with @devin-petersohn to debug this. We tried two methods. 

#### First method 
1.  Copy `adam-assembly-spark2_2.11-0.23.0-SNAPSHOT.jar` from `adam/adam-assembly/target` into the cannoli repo. 
2. In cannoli, run `adam-shell --jars target/cannoli-spark2_2.11-0.1-SNAPSHOT.jar,adam-assembly-spark2_2.11-0.23.0-SNAPSHOT.jar`
3. In adam-shell, try
```
scala> import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.adam.rdd.ADAMContext._

scala> val x = sc.loadFeatures("test.bed")
```

This worked, `sc.loadFeatures` did not cause any errors. 

#### Second method
We then tried adding the additional jar into the original command, which errored.
```
$ ADAM_MAIN=org.bdgenomics.cannoli.Cannoli \
    adam-submit \
    --jars target/cannoli-spark2_2.11-0.1-SNAPSHOT.jar,adam-assembly-spark2_2.11-0.23.0-SNAPSHOT.jar \
    -- \
  macs2 -t test.bed

Using ADAM_MAIN=org.bdgenomics.cannoli.Cannoli
Using SPARK_SUBMIT=/Applications/spark-2.1.1-bin-hadoop2.7/bin/spark-submit
2017-06-30 12:45:33 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Command body threw exception:
java.lang.NoSuchMethodError: org.bdgenomics.adam.rdd.ADAMContext.loadFeatures(Ljava/lang/String;Lscala/Option;Lscala/Option;Lscala/Option;)Lorg/bdgenomics/adam/rdd/feature/FeatureRDD;
Exception in thread "main" java.lang.NoSuchMethodError: org.bdgenomics.adam.rdd.ADAMContext.loadFeatures(Ljava/lang/String;Lscala/Option;Lscala/Option;Lscala/Option;)Lorg/bdgenomics/adam/rdd/feature/FeatureRDD;
	at org.bdgenomics.cannoli.Macs2.run(Macs2.scala:111)
	at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:55)
	at org.bdgenomics.cannoli.Macs2.run(Macs2.scala:94)
	at org.bdgenomics.adam.cli.ADAMMain.apply(ADAMMain.scala:126)
	at org.bdgenomics.cannoli.Cannoli$.main(Cannoli.scala:36)
	at org.bdgenomics.cannoli.Cannoli.main(Cannoli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
Any suggestions on where to go from here? Thank you!

**Comment by fnothaft** [comment]
Hi @gunjanbaid!

Yeah, that method signature issue is a bit tricky to resolve. What should work is to install your local ADAM JAR into your local ~/.m2 Maven repository, and to then build Cannoli against that. To do this, first go to your ADAM directory and do:

```
mvn install
```

This will install ADAM into your local Maven repo (typically `~/.m2`). Then, [change the `adam.version` in your Cannoli pom.xml to 0.23.0-SNAPSHOT](https://github.com/bigdatagenomics/cannoli/blob/master/pom.xml#L38). It'll see that you have ADAM 0.23.0-SNAPSHOT in your local Maven repo, and should compile against that JAR. This should eliminate the signature mismatch that you are encountering.

@heuermh what are your thoughts on adding a `cannoli-submit` here and not relying on an upstream `adam-submit`? I've spent a lot of time working around this exact issue with folks the last few months, and I think that the cost of maintaining a separate `cannoli-submit` is pretty insignificant relative to debugging library incompatibility issues.

**Comment by heuermh** [comment]
Note `--jars` with `adam-shell` doesn't work, see https://github.com/bigdatagenomics/adam/issues/1349

**Comment by heuermh** [comment]
> what are your thoughts on adding a cannoli-submit here and not relying on an upstream adam-submit?

For me I guess the utility is seeing all the ADAM commands when running Cannoli `--help`. Then codewise if we're not reusing `ADAMMain` we'll have to repeat the metrics stuff and perhaps other minor things.  Admittedly those are pretty small benefits.

As discussed previously, I'm more of a lumper than a splitter when it comes to repositories, so personally, I'd like to see all the downstream applications as maven modules in the adam repository.  Then `ADAMMain` could assemble all of those modules into a single set of commands.  There is something to be said for one command that supports an overwhelming amount of functionality.

I'm pretty sure that is a minority opinion though, so if using the `foo-submit` pattern fits better here, I'd be ok with it.

**Comment by gunjanbaid** [comment]
Hi @fnothaft. I did the following:

1. Ran `mvn install` in my adam directory.
2. Updated `adam.version` to `0.23.0-SNAPSHOT` in `pom.xml` in cannoli. 
3. Ran `mvn install` in cannoli. 
4. Ran the following command:
```
ADAM_MAIN=org.bdgenomics.cannoli.Cannoli \
    adam-submit \
    --jars target/cannoli_2.10-0.1-SNAPSHOT.jar \
    -- \
    macs2 -t test.bed
```
 After doing this, I still see the same error:
```
Using ADAM_MAIN=org.bdgenomics.cannoli.Cannoli
Using SPARK_SUBMIT=/Applications/spark-1.6.3-bin-hadoop2.6/bin/spark-submit
2017-07-07 10:11:10 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Command body threw exception:
java.lang.NoSuchMethodError: org.bdgenomics.adam.rdd.ADAMContext.loadFeatures(Ljava/lang/String;Lscala/Option;Lscala/Option;Lscala/Option;)Lorg/bdgenomics/adam/rdd/feature/FeatureRDD;
Exception in thread "main" java.lang.NoSuchMethodError: org.bdgenomics.adam.rdd.ADAMContext.loadFeatures(Ljava/lang/String;Lscala/Option;Lscala/Option;Lscala/Option;)Lorg/bdgenomics/adam/rdd/feature/FeatureRDD;
	at org.bdgenomics.cannoli.Macs2.run(Macs2.scala:111)
	at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:55)
	at org.bdgenomics.cannoli.Macs2.run(Macs2.scala:94)
	at org.bdgenomics.adam.cli.ADAMMain.apply(ADAMMain.scala:126)
	at org.bdgenomics.cannoli.Cannoli$.main(Cannoli.scala:36)
	at org.bdgenomics.cannoli.Cannoli.main(Cannoli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Did I miss anything?

**Comment by heuermh** [comment]
What does `adam-submit` point to?

I have ADAM installed via homebrew, which installs version 0.22.0 to `/usr/local/bin/adam-submit`.
```bash
$ adam-submit --version
Using ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain
Using SPARK_SUBMIT=/usr/local/bin/spark-submit

       e         888~-_          e             e    e
      d8b        888   \        d8b           d8b  d8b
     /Y88b       888    |      /Y88b         d888bdY88b
    /  Y88b      888    |     /  Y88b       / Y88Y Y888b
   /____Y88b     888   /     /____Y88b     /   YY   Y888b
  /      Y88b    888_-~     /      Y88b   /          Y888b

ADAM version: 0.22.0
Built for: Apache Spark 2.1.0, Scala 2.11.8, and Hadoop 2.7.3
```

Homebrew also installs Spark 2.1.1
```bash
$ which spark-submit
/usr/local/bin/spark-submit

$ spark-submit --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.1.1
      /_/
                        
Using Scala version 2.11.8, Java HotSpot(TM) 64-Bit Server VM, 1.8.0_111
```

When developing Cannoli, which as of https://github.com/bigdatagenomics/cannoli/commit/c3d3c57e2cd2f4f349a76eff2c3814fb3f91e01d depends on ADAM version 0.23.0-SNAPSHOT, I build ADAM in a working directory for Spark 2.x and Scala 2.11.
```bash
$ cd working/adam
$ ./scripts/move_to_scala_2.11.sh
$ ./scripts/move_to_spark_2.sh
$ mvn clean install
```

Then use the `adam-submit` in the ADAM working directory for Cannoli
```bash
$ cd ../cannoli
$ mvn clean install
$ ADAM_MAIN=org.bdgenomics.cannoli.Cannoli \
    ../adam/bin/adam-submit \
    --jars target/cannoli-spark2_2.11-0.1-SNAPSHOT.jar \
    --
```

All of the different coordinates (runtime Apache Spark version, Scala version in Apache Spark, Hadoop version in Apache Spark, runtime ADAM version, Apache Spark dependency version in ADAM, Scala dependency version in ADAM, Hadoop dependency version in ADAM, ADAM dependency version in Cannoli, Apache Spark dependency version in Cannoli, Scala dependency version in Cannoli) must match or be close enough to not cause runtime conflicts.

**Comment by gunjanbaid** [comment]
I reinstalled adam through brew and that fixed it. 

I am now using the above versions of `adam-submit` and `spark-submit` in `/usr/local/bin/`. Thanks so much @fnothaft and @heuermh.
