### ISSUE TITLE
Read in Fragment not found

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/cannoli#74]
Hi,
I am getting this error after running cannoli command with bwa.
Command:   ./cannoli-submit bwa hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517848.adam hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homos_sep12.adam SRR1517848 -index  hdfs://ip-10-48-3-5.ips.local:8020/genomics/CannoliTest/Homo_sapience_assembly18.fasta

Error:

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 7, ip-10-48-3-65.ips.local, executor 3): org.apache.parquet.io.InvalidRecordException: Parquet/Avro schema mismatch. Avro field 'readInFragment' not found.
        at org.apache.parquet.avro.AvroIndexedRecordConverter.getAvroField(AvroIndexedRecordConverter.java:128)
        at org.apache.parquet.avro.AvroIndexedRecordConverter.<init>(AvroIndexedRecordConverter.java:89)
        at org.apache.parquet.avro.AvroIndexedRecordConverter.<init>(AvroIndexedRecordConverter.java:64)
        at org.apache.parquet.avro.AvroCompatRecordMaterializer.<init>(AvroCompatRecordMaterializer.java:34)
        at org.apache.parquet.avro.AvroReadSupport.newCompatMaterializer(AvroReadSupport.java:138)
        at org.apache.parquet.avro.AvroReadSupport.prepareForRead(AvroReadSupport.java:130)
        at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:179)
        at org.apache.parquet.hadoop.ParquetRecordReader.initializeInternalReader(ParquetRecordReader.java:201)
        at org.apache.parquet.hadoop.ParquetRecordReader.initialize(ParquetRecordReader.java:145)
        at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:168)
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:133)
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:65)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
17/10/03 05:

**Comment by Rokshan2016** [comment]
Hi,
I simply convert  a fastq file to adam . SRR1517848.fastq to SRR1517848.adam

Do I need to do anything else with the input file?

What does **'readInFragment'** means?

Thanks!
