### ISSUE TITLE
Cannoli-BWA Command Failure

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/cannoli#77]
Hi,
I am using this command :

./cannoli-submit --driver-memory 3g -- bwa hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1518011.fastq hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1518011.adam SRR1518011 -index hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/hg38.fasta -sequence_dictionary hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/hg38.dict -force_load_ifastq

Error :

Driver stacktrace:
17/10/21 23:05:39 INFO scheduler.DAGScheduler: Job 0 failed: saveAsNewAPIHadoopFile at ADAMRDDFunctions.scala:165, took 8.503789 s
Command body threw exception:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 6, ip-10-48-3-12.ips.local, executor 1): java.io.IOException: Cannot run program "bwa": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.bdgenomics.adam.rdd.GenomicRDD$$anonfun$13.apply(GenomicRDD.scala:544)
        at org.bdgenomics.adam.rdd.GenomicRDD$$anonfun$13.apply(GenomicRDD.scala:517)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 16 more

Any suggestion will be helpful!

**Comment by fnothaft** [comment]
Hi @Rokshan2016!

This command assumes that the `bwa` executable is on the `$PATH` on each worker node. If this is not the case, then you need to set the path to the `bwa` executable using the [`-bwa_path` argument](https://github.com/bigdatagenomics/cannoli/blob/master/cli/src/main/scala/org/bdgenomics/cannoli/cli/Bwa.scala#L70). Please reopen if doing that does not solve your problem.

**Comment by Rokshan2016** [comment]
ok. will try that. Thanks

**Comment by Rokshan2016** [comment]
Hi,
I put the bwa executable on the $PATH on each worker node. 
Index file I put in each worker node. 

Command:
 ./cannoli-submit --driver-memory 3g -- bwa -bwa_path /home/rokshan.jahan/adamproject/bwa-master/bwa hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/data/SRR1517974.fastq hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517974.adam SRR1517974 -index /home/rokshan.jahan/adamproject/reference/ref/Homo_sapiens_assembly38.fasta -force_load_ifastq


But now I am having this error:  

17/10/22 22:16:02 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 0
17/10/22 22:16:02 INFO storage.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 24.7 KB, free 529.9 MB)
17/10/22 22:16:02 INFO broadcast.TorrentBroadcast: Reading broadcast variable 0 took 15 ms
17/10/22 22:16:02 INFO serialization.ADAMKryoRegistrator: Did not find Spark internal class. This is expected for Spark 1.
17/10/22 22:16:02 INFO storage.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 377.4 KB, free 529.5 MB)
17/10/22 22:16:03 ERROR util.SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Thread-10,5,main]
java.lang.IllegalArgumentException: Found read name SRR1517974.2 2/1 ending in /1 despite first-of-pair flag being set
	at org.bdgenomics.adam.converters.FastqRecordConverter.readNameSuffixAndIndexOfPairMustMatch(FastqRecordConverter.scala:65)
	at org.bdgenomics.adam.converters.FastqRecordConverter.parseReadInFastq(FastqRecordConverter.scala:87)
	at org.bdgenomics.adam.converters.FastqRecordConverter.parseReadPairInFastq(FastqRecordConverter.scala:138)
	at org.bdgenomics.adam.converters.FastqRecordConverter.convertFragment(FastqRecordConverter.scala:235)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadInterleavedFastqAsFragments$1$$anonfun$apply$16.apply(ADAMContext.scala:2206)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadInterleavedFastqAsFragments$1$$anonfun$apply$16.apply(ADAMContext.scala:2206)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at org.bdgenomics.adam.rdd.fragment.InterleavedFASTQInFormatter.write(InterleavedFASTQInFormatter.scala:71)
	at org.bdgenomics.adam.rdd.InFormatterRunner.run(InFormatter.scala:27)
	at java.lang.Thread.run(Thread.java:748)
17/10/22 22:16:03 INFO storage.DiskBlockManager: Shutdown hook called
17/10/22 22:16:03 INFO util.ShutdownHookManager: Shutdown hook called
17/10/22 22:16:03 INFO util.ShutdownHookManager: Dele

**Comment by Rokshan2016** [comment]
Hi @fnothaft 
I am not understanding what does this means 

 Found read name SRR1517974.2 2/1 ending in /1 despite first-of-pair flag being set
