### ISSUE TITLE
Cannoli-BWA Command Failure // Re Open

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/cannoli#78]
Hi @fnothaft
I put the bwa executable on the $PATH on each worker node.
Index file I put in each worker node.

Command:
./cannoli-submit --driver-memory 3g -- bwa -bwa_path /home/rokshan.jahan/adamproject/bwa-master/bwa hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/data/SRR1517974.fastq hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517974.adam SRR1517974 -index /home/rokshan.jahan/adamproject/reference/ref/Homo_sapiens_assembly38.fasta -force_load_ifastq

But now I am having this error:

17/10/22 22:16:02 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 0
17/10/22 22:16:02 INFO storage.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 24.7 KB, free 529.9 MB)
17/10/22 22:16:02 INFO broadcast.TorrentBroadcast: Reading broadcast variable 0 took 15 ms
17/10/22 22:16:02 INFO serialization.ADAMKryoRegistrator: Did not find Spark internal class. This is expected for Spark 1.
17/10/22 22:16:02 INFO storage.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 377.4 KB, free 529.5 MB)
17/10/22 22:16:03 ERROR util.SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Thread-10,5,main]
java.lang.IllegalArgumentException: Found read name SRR1517974.2 2/1 ending in /1 despite first-of-pair flag being set
at org.bdgenomics.adam.converters.FastqRecordConverter.readNameSuffixAndIndexOfPairMustMatch(FastqRecordConverter.scala:65)
at org.bdgenomics.adam.converters.FastqRecordConverter.parseReadInFastq(FastqRecordConverter.scala:87)
at org.bdgenomics.adam.converters.FastqRecordConverter.parseReadPairInFastq(FastqRecordConverter.scala:138)
at org.bdgenomics.adam.converters.FastqRecordConverter.convertFragment(FastqRecordConverter.scala:235)
at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadInterleavedFastqAsFragments$1$$anonfun$apply$16.apply(ADAMContext.scala:2206)
at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadInterleavedFastqAsFragments$1$$anonfun$apply$16.apply(ADAMContext.scala:2206)
at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
at scala.collection.Iterator$class.foreach(Iterator.scala:727)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
at org.bdgenomics.adam.rdd.fragment.InterleavedFASTQInFormatter.write(InterleavedFASTQInFormatter.scala:71)
at org.bdgenomics.adam.rdd.InFormatterRunner.run(InFormatter.scala:27)
at java.lang.Thread.run(Thread.java:748)
17/10/22 22:16:03 INFO storage.DiskBlockManager: Shutdown hook called
17/10/22 22:16:03 INFO util.ShutdownHookManager: Shutdown hook called
17/10/22 22:16:03 INFO util.ShutdownHookManager: Dele

**Comment by Rokshan2016** [comment]
Hi @fnothaft
I am not understanding what does this means

Found read name SRR1517974.2 2/1 ending in /1 despite first-of-pair flag being set

**Comment by heuermh** [comment]
Is that read supposed to be the first or second of a pair of reads?

The name may have confused our regular expressions
https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/FastqRecordConverter.scala#L43
https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/FastqRecordConverter.scala#L44

**Comment by Rokshan2016** [comment]
resolved
