### ISSUE TITLE
Error with snpEff

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/cannoli#86]
Hi,
I am trying to use cannoli with snpEff. 
Here is my command -
./cannoli-submit snpEff hdfs://ip-10-48-3-5.ips.local:8020/genomics/VCF_FILE/SRR1517974.vcf hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1.vcf -database GRCh38.82

I am getting this error -
17/11/07 12:28:10 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on ip-10-48-3-12.ips.local:37891 (size: 24.7 KB, free: 530.0 MB)
17/11/07 12:28:11 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, ip-10-48-3-12.ips.local, executor 1): java.lang.ArrayIndexOutOfBoundsException: -2147483648
        at org.bdgenomics.adam.util.PhredUtils$.phredToSuccessProbability(PhredUtils.scala:68)
        at org.bdgenomics.adam.util.PhredUtils$.phredToLogProbability(PhredUtils.scala:56)
        at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$formatNonRefGenotypeLikelihoods$1.apply(VariantContextConverter.scala:863)
        at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$formatNonRefGenotypeLikelihoods$1.apply(VariantContextConverter.scala:862)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofInt.foreach(ArrayOps.scala:156)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.mutable.ArrayOps$ofInt.map(ArrayOps.scala:156)
        at org.bdgenomics.adam.converters.VariantContextConverter.formatNonRefGenotypeLikelihoods(VariantContextConverter.scala:862)
        at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$80.apply(VariantContextConverter.scala:1739)
        at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$80.apply(VariantContextConverter.scala:1734)
        at scala.Option.fold(Option.scala:157)
        at org.bdgenomics.adam.converters.VariantContextConverter.org$bdgenomics$adam$converters$VariantContextConverter$$convert$2(VariantContextConverter.scala:1734)
        at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$makeGenotypeFormatFn$1.apply(VariantContextConverter.scala:1787)
        at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$makeGenotypeFormatFn$1.apply(VariantContextConverter.scala:1787)
        at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$5.apply(VariantContextConverter.scala:318)
        at org.bdgenomics.adam.converters.VariantContextConverter$$anonfun$5.apply(VariantContextConverter.scala:317)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at org.bdgenomics.adam.converters.VariantContextConverter.convert(VariantContextConverter.scala:317)
        at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadVcf$1$$anonfun$apply$14.apply(ADAMContext.scala:2017)
        at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadVcf$1$$anonfun$apply$14.apply(ADAMContext.scala:2017)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Any suggestion will be helpful

Thanks!

**Comment by heuermh** [comment]
Closing in favor of https://github.com/bigdatagenomics/adam/issues/1714 upstream.
